---

nginx_confs: []

nginx_certbot: true
certbot_regenerate: false
nginx_certbot_use_dns_challenge: false

nginx_proxy_headers:
  X-Forwarded-For: '$remote_addr'
  X-Real-IP: '$remote_addr'
  X-Forwarded-Proto: '$scheme'
  Host: '$host'
  Upgrade: '$http_upgrade'
  Connection: '$connection_upgrade'
